/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ujun;

import java.util.List;
import java.util.LinkedList;
import java.util.Map;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class AppView extends javax.swing.JFrame {

    private final Map<String, Double> daftarKopon = Map.of(
            "KUPON1", 0.1,
            "KUPON2", 0.2,
            "KUPON3", 0.3,
            "UNISKA_KUPON", 0.4
    );

    private final Map<String, Double> daftarDiskon = Map.of(
            "10%", 0.1,
            "20%", 0.2,
            "30%", 0.3
    );

    private List<String[]> riwayat = new LinkedList<>();

    public AppView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDiskon = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldHargaAsli = new javax.swing.JTextField();
        comboBoxDiskon = new javax.swing.JComboBox<>();
        sliderDiskon = new javax.swing.JSlider();
        fieldKuponDiskon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        paneHargaAkhir = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        paneJumlahPenghematan = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        buttonHitung = new javax.swing.JButton();
        radioButtonComboBox = new javax.swing.JRadioButton();
        radioButtonSlider = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 35));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setText("APLIKASI HITUNG DISKON");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jLabel2.setText("Harga Asli");

        jLabel3.setText("Pilih Diskon");

        jLabel5.setText("Kupon Diskon");

        comboBoxDiskon.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak diskon", "10%", "20%", "30%" }));
        comboBoxDiskon.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxDiskonItemStateChanged(evt);
            }
        });

        sliderDiskon.setMajorTickSpacing(20);
        sliderDiskon.setPaintLabels(true);
        sliderDiskon.setPaintTicks(true);
        sliderDiskon.setValue(0);
        sliderDiskon.setEnabled(false);

        jScrollPane1.setViewportView(paneHargaAkhir);

        jScrollPane2.setViewportView(paneJumlahPenghematan);

        jLabel6.setText("Harga Akhir");

        jLabel7.setText("Jumlah Penghematan");

        buttonHitung.setText("Hitung");
        buttonHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHitungActionPerformed(evt);
            }
        });

        buttonGroupDiskon.add(radioButtonComboBox);
        radioButtonComboBox.setSelected(true);
        radioButtonComboBox.setText("combo box");
        radioButtonComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonComboBoxItemStateChanged(evt);
            }
        });

        buttonGroupDiskon.add(radioButtonSlider);
        radioButtonSlider.setText("slider");
        radioButtonSlider.setName(""); // NOI18N
        radioButtonSlider.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radioButtonSliderItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(fieldKuponDiskon)
                    .addComponent(buttonHitung, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(fieldHargaAsli)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioButtonComboBox)
                            .addComponent(radioButtonSlider))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sliderDiskon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addComponent(comboBoxDiskon, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1))
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fieldHargaAsli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(comboBoxDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButtonComboBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radioButtonSlider))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(fieldKuponDiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonHitung)
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Riwayat"));
        jPanel3.setPreferredSize(new java.awt.Dimension(548, 260));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Harga Asli", "Harga Akhir", "Jumlah Penghematan"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 617, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHitungActionPerformed
        this.hitungDiskon();
    }//GEN-LAST:event_buttonHitungActionPerformed

    boolean s = false;
    private void comboBoxDiskonItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxDiskonItemStateChanged
        this.hitungDiskon();
        s = !s;
        if (s) {
            this.riwayat.removeLast();
        }
    }//GEN-LAST:event_comboBoxDiskonItemStateChanged

    private void radioButtonSliderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonSliderItemStateChanged
        sliderDiskon.setEnabled(true);
        comboBoxDiskon.setEnabled(false);
    }//GEN-LAST:event_radioButtonSliderItemStateChanged

    private void radioButtonComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radioButtonComboBoxItemStateChanged
        sliderDiskon.setEnabled(false);
        comboBoxDiskon.setEnabled(true);
    }//GEN-LAST:event_radioButtonComboBoxItemStateChanged

    private void hitungDiskon() {
        try {
            if(!this.daftarKopon.containsKey(fieldKuponDiskon.getText()) && !fieldKuponDiskon.getText().isBlank()){
                JOptionPane.showMessageDialog(null, "Kupon yg dimasukkan tidak terdaftar");
                return;
            }
            
            int hargaAsli = Integer.parseInt(fieldHargaAsli.getText());
            double diskon = 0;
            double diskonKupon = Optional.ofNullable(this.daftarKopon.get(fieldKuponDiskon.getText()))
                    .orElse(0d);
            if (radioButtonComboBox.isSelected()) {
                try {
                    diskon = this.daftarDiskon.get(comboBoxDiskon.getSelectedItem().toString());
                } catch (Throwable e) {
                    diskon = 0;
                }
            } else if (radioButtonSlider.isSelected()) {
                diskon = sliderDiskon.getValue() / 100f;
            }

            double penghematanDiskon = hargaAsli * diskon;
            double penghematanKuponDiskon = hargaAsli * diskonKupon;
            double jumlahPenghematan = penghematanDiskon + penghematanKuponDiskon;
            double hargaAkhir = hargaAsli - jumlahPenghematan;

            paneHargaAkhir.setText("Rp. %.2f".formatted(hargaAkhir));
            paneJumlahPenghematan.setText("Rp. %.2f".formatted(jumlahPenghematan));

            this.riwayat.add(new String[]{
                "%d".formatted(hargaAsli),
                "%.2f".formatted(hargaAkhir),
                "%.2f".formatted(jumlahPenghematan)
            });
            this.tampilkanRiwayat();
        } catch (Throwable e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    public void tampilkanRiwayat() {
        var tableModel = (DefaultTableModel) jTable1.getModel();
        tableModel.setRowCount(0);
        for (int i = 0; i < this.riwayat.size(); i++) {
            var row = this.riwayat.get(i);
            tableModel.addRow(new String[]{String.valueOf(i+1), row[0], row[1], row[2]});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDiskon;
    private javax.swing.JButton buttonHitung;
    private javax.swing.JComboBox<String> comboBoxDiskon;
    private javax.swing.JTextField fieldHargaAsli;
    private javax.swing.JTextField fieldKuponDiskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane paneHargaAkhir;
    private javax.swing.JTextPane paneJumlahPenghematan;
    private javax.swing.JRadioButton radioButtonComboBox;
    private javax.swing.JRadioButton radioButtonSlider;
    private javax.swing.JSlider sliderDiskon;
    // End of variables declaration//GEN-END:variables
}
